export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS';
export const NEW_POSTS = 'NEW_POSTS';
export const SIGN_IN = 'SIGN_IN';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const ACCOUNT_ALREADY_EXITS = 'ACCOUNT_ALREADY_EXITS';
export const INCORRECT_LOGIN_INFORMATION = 'INCORRECT_LOGIN_INFORMATION';
